// Generated by scripts/stamp-version.sh — do not edit, and do not bump: the version's
// home is the git tag, and scripts/version.sh explains how it gets here. The value
// committed here is the one a plain checkout builds with. See Decision 0013.
public enum MynahVersion {
    public static let current = "0.0.0-dev"
}
