#!/bin/sh
# Generate cli/Sources/MynahCore/MynahVersion.swift from scripts/version.sh.
#
# The Swift file has to exist in the tree for a bare `swift build` to work, so it is
# committed — carrying the checkout version, "0.0.0-dev". Every build regenerates it.
set -eu

cd "$(dirname "$0")/.."

OUT=cli/Sources/MynahCore/MynahVersion.swift
V="$(scripts/version.sh)"

TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

cat > "$TMP" <<EOF
// Generated by scripts/stamp-version.sh — do not edit, and do not bump: the version's
// home is the git tag, and scripts/version.sh explains how it gets here. The value
// committed here is the one a plain checkout builds with. See Decision 0013.
public enum MynahVersion {
    public static let current = "$V"
}
EOF

# Rewrite only on a real change. An unconditional write would touch the file on every
# build and make SwiftPM recompile MynahCore — and everything above it — for nothing.
if cmp -s "$TMP" "$OUT"; then
    exit 0
fi
cp "$TMP" "$OUT"
